import { Teacher } from './types'

export const demoTeachers: Teacher[] = [
  {
    id: '1',
    name: 'Dr. Selin Aksoy',
    email: 'selin.aksoy@demo.com',
    branch: 'Matematik',
    title: 'Dr. Öğretim Üyesi',
    joinDate: '2023-09-01',
    avatar: '👩‍🏫',
    phone: '+90 532 123 4567',
    office: '201',
    department: 'Fen Bilimleri',
    experience: '5 yıl',
    education: 'ODTÜ Matematik Bölümü - Doktora',
    expertise: ['Cebir', 'Geometri', 'Matematik Analizi', 'İstatistik'],
    publications: 12,
    awards: ['En İyi Öğretmen 2023', 'Bilim Ödülü 2022'],
    rating: 4.8
  },
  {
    id: '2',
    name: 'Ahmet Yılmaz',
    email: 'ahmet.yilmaz@demo.com',
    branch: 'Fizik',
    title: 'Öğretmen',
    joinDate: '2022-09-01',
    avatar: '👨‍🏫',
    phone: '+90 533 234 5678',
    office: 'Lab-1',
    department: 'Fen Bilimleri',
    experience: '8 yıl',
    education: 'Boğaziçi Üniversitesi Fizik Bölümü - Yüksek Lisans',
    expertise: ['Mekanik', 'Elektrik', 'Manyetizma', 'Modern Fizik'],
    publications: 5,
    awards: ['Lab Ödülü 2023', 'TÜBİTAK Proje Ödülü'],
    rating: 4.6
  },
  {
    id: '3',
    name: 'Zeynep Kaya',
    email: 'zeynep.kaya@demo.com',
    branch: 'Kimya',
    title: 'Uzman Öğretmen',
    joinDate: '2021-09-01',
    avatar: '👩‍🏫',
    phone: '+90 534 345 6789',
    office: 'Lab-2',
    department: 'Fen Bilimleri',
    experience: '12 yıl',
    education: 'İTÜ Kimya Mühendisliği - Yüksek Lisans',
    expertise: ['Organik Kimya', 'Anorganik Kimya', 'Fizikokimya', 'Analitik Kimya'],
    publications: 8,
    awards: ['Kimya Ödülü 2023', 'Proje Başarısı 2022'],
    rating: 4.9
  },
  {
    id: '4',
    name: 'Mehmet Demir',
    email: 'mehmet.demir@demo.com',
    branch: 'Türkçe',
    title: 'Öğretmen',
    joinDate: '2020-09-01',
    avatar: '👨‍🏫',
    phone: '+90 535 456 7890',
    office: '102',
    department: 'Edebiyat',
    experience: '15 yıl',
    education: 'İstanbul Üniversitesi Türk Dili ve Edebiyatı - Yüksek Lisans',
    expertise: ['Edebiyat', 'Dil Bilgisi', 'Kompozisyon', 'Okuma'],
    publications: 3,
    awards: ['En İyi Eğitimci 2023', 'Yazarlık Ödülü 2022'],
    rating: 4.7
  },
  {
    id: '5',
    name: 'Ayşe Öztürk',
    email: 'ayse.ozturk@demo.com',
    branch: 'Biyoloji',
    title: 'Öğretmen',
    joinDate: '2024-09-01',
    avatar: '👩‍🏫',
    phone: '+90 536 567 8901',
    office: 'Lab-3',
    department: 'Fen Bilimleri',
    experience: '3 yıl',
    education: 'Ankara Üniversitesi Biyoloji Bölümü - Yüksek Lisans',
    expertise: ['Bitki Bilimi', 'Hayvan Bilimi', 'Genetik', 'Ekoloji'],
    publications: 2,
    awards: ['Genç Araştırmacı Ödülü 2024'],
    rating: 4.5
  },
  {
    id: '6',
    name: 'Mustafa Arslan',
    email: 'mustafa.arslan@demo.com',
    branch: 'Tarih',
    title: 'Uzman Öğretmen',
    joinDate: '2019-09-01',
    avatar: '👨‍🏫',
    phone: '+90 537 678 9012',
    office: '103',
    department: 'Sosyal Bilimler',
    experience: '20 yıl',
    education: 'Marmara Üniversitesi Tarih Bölümü - Doktora',
    expertise: ['Türk Tarihi', 'Dünya Tarihi', 'Osmanlı Tarihi', 'Arkeoloji'],
    publications: 15,
    awards: ['Tarih Araştırma Ödülü 2023', 'En İyi Öğretmen 2022'],
    rating: 4.8
  }
]